POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
  "name" : "akhil",
  "email" : "akhil@gmail.com",
  "password" : "12345"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email" : "akhil@gmail.com",
  "password" : "12345"
}

###

POST http://localhost:5000/api/users/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjQ2YTY4NDE4MDQ3OTA3MGEyMDc2NmNmIiwiaWF0IjoxNjg0NzY3ODg3fQ.03OpNrbhsuVpjc0BmLZEh6WcrxLdSJecW1zCk6e1Aig

###

GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjQ2YTY4NDE4MDQ3OTA3MGEyMDc2NmNmIiwiaWF0IjoxNjg0NzY3ODg3fQ.03OpNrbhsuVpjc0BmLZEh6WcrxLdSJecW1zCk6e1Aig

###

GET http://localhost:5000/api/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjQ2YTY4NDE4MDQ3OTA3MGEyMDc2NmNmIiwiaWF0IjoxNjg0NzY3ODg3fQ.03OpNrbhsuVpjc0BmLZEh6WcrxLdSJecW1zCk6e1Aig